import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { getWardrobe } from '../../services/api/wardrobe';
import { CATEGORY_MAP, COLORS } from '../../constants/categories';
import { Filter, Plus, Search, Shirt } from 'lucide-react';

export default function Wardrobe() {
  const [category, setCategory] = useState(''); const [color, setColor] = useState(''); const [search, setSearch] = useState('');
  const { data, isLoading } = useQuery({ queryKey: ['wardrobe', { category, color }], queryFn: () => getWardrobe({ category: category || undefined, color: color || undefined, limit: 48 }) });
  const items = (data?.data || []).filter((item) => `${item.subcategory} ${item.brand || ''}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="mx-auto max-w-7xl p-5 sm:p-8"><header className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold text-brand-purple-600">CLOSET</p><h1 className="mt-1 text-3xl font-black">My wardrobe</h1></div><Link to="/wardrobe/add" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-brand-purple-600 to-brand-pink-500 px-5 py-3 text-sm font-bold text-white"><Plus className="h-4 w-4" />Add clothing</Link></header>
    <div className="mt-7 grid gap-3 rounded-2xl border border-slate-200 bg-white p-3 dark:border-slate-800 dark:bg-slate-900 md:grid-cols-[1fr_180px_180px]"><label className="flex items-center gap-2 rounded-xl bg-slate-50 px-3 dark:bg-slate-800"><Search className="h-4 w-4 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search brand or item" className="w-full bg-transparent py-3 text-sm outline-none" /></label><select value={category} onChange={(event) => setCategory(event.target.value)} className="rounded-xl bg-slate-50 px-3 text-sm outline-none dark:bg-slate-800"><option value="">All categories</option>{Object.keys(CATEGORY_MAP).map((value) => <option key={value} value={value}>{value}</option>)}</select><select value={color} onChange={(event) => setColor(event.target.value)} className="rounded-xl bg-slate-50 px-3 text-sm outline-none dark:bg-slate-800"><option value="">All colours</option>{COLORS.map((entry) => <option key={entry.value} value={entry.value}>{entry.label}</option>)}</select></div>
    <div className="mt-4 flex items-center gap-2 text-sm text-slate-500"><Filter className="h-4 w-4" />{items.length} item{items.length === 1 ? '' : 's'} shown</div>
    {isLoading ? <p className="mt-8 text-sm text-slate-500">Loading wardrobe…</p> : items.length ? <div className="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">{items.map((item) => <Link key={item.id} to={`/wardrobe/${item.id}`} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-md dark:border-slate-800 dark:bg-slate-900"><div className="relative aspect-[4/5] overflow-hidden bg-slate-100"><img src={item.imageUrl} alt={item.subcategory} className="h-full w-full object-cover transition duration-300 group-hover:scale-105" /><span className="absolute left-2 top-2 rounded-lg bg-white/90 px-2 py-1 text-[10px] font-bold text-slate-600">{item.laundryStatus}</span></div><div className="p-3"><p className="text-[10px] font-black uppercase tracking-wider text-brand-purple-600">{item.category}</p><h2 className="mt-1 truncate text-sm font-bold">{item.subcategory}</h2><p className="mt-1 truncate text-xs text-slate-500">{item.brand || 'Unbranded'}</p></div></Link>)}</div> : <div className="mt-8 rounded-3xl border border-dashed border-slate-300 p-12 text-center"><Shirt className="mx-auto h-8 w-8 text-slate-400" /><h2 className="mt-3 text-lg font-black">No clothing found</h2><p className="mt-1 text-sm text-slate-500">Try adjusting your filters or add a new item.</p></div>}</div>;
}
