import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { ChevronLeft, ChevronRight, Filter, Plus, Search, Shirt, SlidersHorizontal, X } from 'lucide-react';
import { getWardrobe } from '../../services/api/wardrobe';
import { CATEGORY_MAP, COLORS, LAUNDRY_STATUSES, OCCASIONS, SEASONS } from '../../constants/categories';

const initialFilters = { category: '', color: '', occasion: '', brand: '', season: '', laundryStatus: '', search: '', sort: 'newest', page: 1, limit: 12 };
const selectClass = 'w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 text-sm outline-none transition focus:border-brand-purple-500 dark:border-slate-700 dark:bg-slate-800 dark:text-white';

export default function Wardrobe() {
  const [filters, setFilters] = useState(initialFilters); const [showFilters, setShowFilters] = useState(false);
  const update = (key, value) => setFilters((current) => ({ ...current, [key]: value, page: key === 'page' ? value : 1 }));
  const params = Object.fromEntries(Object.entries(filters).filter(([, value]) => value !== ''));
  const { data, isLoading, isFetching } = useQuery({ queryKey: ['wardrobe', filters], queryFn: () => getWardrobe(params), placeholderData: (previous) => previous });
  const items = data?.data || []; const pagination = data?.pagination;
  return <div className="mx-auto max-w-7xl p-5 sm:p-8"><header className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold text-brand-purple-600">CLOSET</p><h1 className="mt-1 text-3xl font-black">My wardrobe</h1><p className="mt-1 text-sm text-slate-500">Search, filter, and manage every piece you own.</p></div><Link to="/wardrobe/add" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-brand-purple-600 to-brand-pink-500 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-brand-purple-500/15"><Plus className="h-4 w-4" />Add clothes</Link></header>
    <section className="mt-7 rounded-3xl border border-slate-100 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-col gap-3 md:flex-row"><label className="flex flex-1 items-center gap-2 rounded-xl bg-slate-50 px-3 dark:bg-slate-800"><Search className="h-4 w-4 text-slate-400" /><input value={filters.search} onChange={(event) => update('search', event.target.value)} placeholder="Search clothing, brand, or notes" className="w-full bg-transparent py-3 text-sm outline-none dark:text-white" /></label><select value={filters.sort} onChange={(event) => update('sort', event.target.value)} className="rounded-xl bg-slate-50 px-3 py-3 text-sm outline-none dark:bg-slate-800 dark:text-white"><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="name-asc">Name A–Z</option><option value="name-desc">Name Z–A</option></select><button onClick={() => setShowFilters((value) => !value)} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold dark:border-slate-700"><SlidersHorizontal className="h-4 w-4" />Filters</button></div>
      {showFilters && <div className="mt-4 grid gap-3 border-t border-slate-100 pt-4 dark:border-slate-800 sm:grid-cols-2 lg:grid-cols-3"><select value={filters.category} onChange={(event) => update('category', event.target.value)} className={selectClass}><option value="">All categories</option>{Object.keys(CATEGORY_MAP).map((value) => <option key={value} value={value}>{value}</option>)}</select><select value={filters.color} onChange={(event) => update('color', event.target.value)} className={selectClass}><option value="">All colours</option>{COLORS.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><select value={filters.occasion} onChange={(event) => update('occasion', event.target.value)} className={selectClass}><option value="">All occasions</option>{OCCASIONS.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><input value={filters.brand} onChange={(event) => update('brand', event.target.value)} placeholder="Filter by brand" className={selectClass} /><select value={filters.season} onChange={(event) => update('season', event.target.value)} className={selectClass}><option value="">All seasons</option>{SEASONS.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><select value={filters.laundryStatus} onChange={(event) => update('laundryStatus', event.target.value)} className={selectClass}><option value="">All laundry statuses</option>{LAUNDRY_STATUSES.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><button onClick={() => setFilters(initialFilters)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-100 px-3 py-3 text-sm font-bold text-slate-600 dark:bg-slate-800 dark:text-slate-300"><X className="h-4 w-4" />Clear filters</button></div>}</section>
    <div className="mt-5 flex items-center gap-2 text-sm text-slate-500"><Filter className="h-4 w-4" />{pagination?.total ?? 0} item{pagination?.total === 1 ? '' : 's'} {isFetching && !isLoading ? '· Updating…' : ''}</div>
    {isLoading ? <div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">{Array.from({ length: 10 }).map((_, index) => <div key={index} className="aspect-[3/4] animate-pulse rounded-2xl bg-slate-200 dark:bg-slate-800" />)}</div> : items.length ? <><div className="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">{items.map((item) => <Link key={item.id} to={`/wardrobe/${item.id}`} className="group overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-md dark:border-slate-800 dark:bg-slate-900"><div className="relative aspect-[4/5] overflow-hidden bg-slate-100 dark:bg-slate-800"><img src={item.imageUrl} alt={item.subcategory} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><span className="absolute left-2 top-2 rounded-lg bg-white/90 px-2 py-1 text-[10px] font-bold text-slate-600 dark:bg-slate-950/85 dark:text-slate-300">{item.laundryStatus}</span></div><div className="p-3"><p className="text-[10px] font-black uppercase tracking-wider text-brand-purple-600">{item.category}</p><h2 className="mt-1 truncate text-sm font-bold">{item.subcategory}</h2><p className="mt-1 truncate text-xs text-slate-500">{item.brand || 'Unbranded'}</p></div></Link>)}</div>{pagination?.totalPages > 1 && <nav className="mt-8 flex items-center justify-center gap-3"><button disabled={pagination.page <= 1} onClick={() => update('page', pagination.page - 1)} className="inline-flex items-center gap-1 rounded-xl border border-slate-200 px-3 py-2 text-sm font-bold disabled:opacity-40 dark:border-slate-700"><ChevronLeft className="h-4 w-4" />Previous</button><span className="text-sm text-slate-500">Page {pagination.page} of {pagination.totalPages}</span><button disabled={pagination.page >= pagination.totalPages} onClick={() => update('page', pagination.page + 1)} className="inline-flex items-center gap-1 rounded-xl border border-slate-200 px-3 py-2 text-sm font-bold disabled:opacity-40 dark:border-slate-700">Next<ChevronRight className="h-4 w-4" /></button></nav>}</> : <div className="mt-8 rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center dark:border-slate-700 dark:bg-slate-900"><Shirt className="mx-auto h-8 w-8 text-slate-400" /><h2 className="mt-3 text-lg font-black">No clothing found</h2><p className="mt-1 text-sm text-slate-500">Try changing your filters or add a new clothing item.</p><button onClick={() => setFilters(initialFilters)} className="mt-4 text-sm font-bold text-brand-purple-600">Clear all filters</button></div>}</div>;
}
