import React from 'react';
import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { Bell, CalendarDays, ChevronRight, CloudSun, Heart, Plus, Shirt, Sparkles, WashingMachine } from 'lucide-react';
import { getWardrobe } from '../services/api/wardrobe';
import { useAuth } from '../context/AuthContext';

const categoryMeta = [{ key: 'TOPS', label: 'Tops', emoji: '👕', tone: 'bg-emerald-50' }, { key: 'BOTTOMS', label: 'Bottoms', emoji: '👖', tone: 'bg-blue-50' }, { key: 'DRESSES', label: 'Dresses', emoji: '👗', tone: 'bg-violet-50' }, { key: 'FOOTWEAR', label: 'Shoes', emoji: '👟', tone: 'bg-amber-50' }, { key: 'ACCESSORIES', label: 'Bags & accessories', emoji: '👜', tone: 'bg-orange-50' }];
const format = (value) => value ? value.charAt(0) + value.slice(1).toLowerCase().replaceAll('_', ' ') : '';

function WardrobeCard({ item }) { return <Link to={`/wardrobe/${item.id}`} className="group overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-md dark:border-slate-800 dark:bg-slate-900"><div className="relative aspect-[4/5] overflow-hidden bg-slate-100"><img src={item.imageUrl} alt={item.subcategory} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><Heart className="absolute right-3 top-3 h-4 w-4 text-white drop-shadow" /></div><div className="p-3"><strong className="block truncate text-sm">{item.subcategory}</strong><span className="mt-1 block text-xs text-slate-400">{format(item.category)}</span></div></Link>; }
function Stat({ icon: Icon, label, value, sub, className }) { return <div className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className={`grid h-10 w-10 place-items-center rounded-xl ${className}`}><Icon className="h-5 w-5" /></div><strong className="mt-4 block text-3xl">{value}</strong><span className="mt-1 block text-sm font-semibold">{label}</span><small className="text-xs text-slate-400">{sub}</small></div>; }

export default function Dashboard() {
  const { user } = useAuth(); const { data, isLoading } = useQuery({ queryKey: ['wardrobe', 'dashboard-ui'], queryFn: () => getWardrobe({ limit: 100 }) });
  const items = data?.data || []; const total = data?.pagination?.total || 0; const available = items.filter((item) => item.laundryStatus === 'AVAILABLE').length; const favorites = items.filter((item) => item.isFavorite).length;
  const count = (key) => key === 'DRESSES' ? items.filter((item) => ['Dress', 'Jumpsuit'].includes(item.subcategory)).length : items.filter((item) => item.category === key).length;
  const hour = new Date().getHours(); const greeting = hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening';
  return <div className="mx-auto max-w-[1450px] px-4 py-6 sm:px-7 lg:px-9"><header className="flex items-center justify-between"><div className="lg:hidden"><span className="text-lg font-black">DripLy</span></div><div className="hidden lg:block" /><div className="flex items-center gap-4"><button aria-label="Notifications" className="rounded-full p-2 text-slate-500 hover:bg-white"><Bell className="h-5 w-5" /></button><Link to="/profile" className="grid h-9 w-9 place-items-center rounded-full bg-brand-purple-100 font-black text-brand-purple-700">{user?.name?.[0]?.toUpperCase() || 'D'}</Link></div></header>
    <section className="mt-8 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-black tracking-tight sm:text-4xl">{greeting}, {user?.name?.split(' ')[0] || 'there'} <span>☀️</span></h1><p className="mt-2 text-sm text-slate-500">Let’s find your perfect outfit for today.</p></div><Link to="/wardrobe/add" className="inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-brand-purple-600 to-brand-pink-500 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-brand-purple-500/15"><Plus className="h-4 w-4" />Add clothes</Link></section>
    <section className="mt-7 grid gap-4 sm:grid-cols-3"><Stat icon={Shirt} label="My wardrobe" value={total} sub="Items" className="bg-brand-purple-50 text-brand-purple-600" /><Stat icon={Sparkles} label="Outfits" value="—" sub="Coming soon" className="bg-violet-50 text-violet-600" /><Stat icon={Heart} label="Favorites" value={favorites} sub="Saved pieces" className="bg-rose-50 text-rose-500" /></section>
    <section className="mt-9"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">AI outfit suggestions</h2><p className="mt-1 text-sm text-slate-500">Your saved wardrobe will power personalized looks.</p></div><span className="rounded-full bg-brand-purple-50 px-3 py-1 text-xs font-bold text-brand-purple-700">Coming soon</span></div><div className="mt-4 rounded-3xl border border-dashed border-brand-purple-200 bg-gradient-to-r from-brand-purple-50 to-brand-pink-50 p-6 dark:border-brand-purple-900 dark:from-brand-purple-950/25 dark:to-brand-pink-950/20 sm:p-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="max-w-xl"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white text-brand-purple-600 shadow-sm"><Sparkles className="h-5 w-5" /></span><h3 className="mt-4 text-lg font-black">Outfit suggestions are nearly ready</h3><p className="mt-1 text-sm text-slate-500">Add a few pieces across tops, bottoms, dresses, and shoes. The upcoming rule-based stylist will create combinations from only your wardrobe.</p></div><Link to="/wardrobe/add" className="inline-flex shrink-0 items-center gap-1 text-sm font-bold text-brand-purple-700">Add an item <ChevronRight className="h-4 w-4" /></Link></div></div></section>
    <section className="mt-9"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Your wardrobe overview</h2><Link to="/wardrobe" className="text-sm font-bold text-brand-purple-600">View all</Link></div><div className="mt-4 grid grid-cols-2 gap-3 rounded-3xl border border-slate-100 bg-white p-3 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:grid-cols-3 lg:grid-cols-5">{categoryMeta.map((category) => <Link to="/wardrobe" key={category.key} className="flex items-center gap-3 rounded-2xl p-3 transition hover:bg-slate-50 dark:hover:bg-slate-800"><span className={`grid h-10 w-10 place-items-center rounded-xl text-xl ${category.tone}`}>{category.emoji}</span><span><strong className="block text-sm">{category.label}</strong><small className="text-xs text-slate-400">{count(category.key)} items</small></span></Link>)}</div></section>
    <section className="mt-9 grid gap-6 xl:grid-cols-[1.7fr_.7fr]"><div><div className="flex items-center justify-between"><h2 className="text-xl font-black">My wardrobe</h2><Link to="/wardrobe" className="text-sm font-bold text-brand-purple-600">View all</Link></div>{isLoading ? <p className="mt-5 text-sm text-slate-500">Loading wardrobe…</p> : items.length ? <div className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">{items.slice(0, 8).map((item) => <WardrobeCard key={item.id} item={item} />)}</div> : <div className="mt-4 rounded-3xl border border-dashed border-slate-300 bg-white p-10 text-center dark:border-slate-700 dark:bg-slate-900"><Shirt className="mx-auto h-8 w-8 text-slate-400" /><h3 className="mt-3 font-black">Your wardrobe is empty</h3><Link to="/wardrobe/add" className="mt-3 inline-block text-sm font-bold text-brand-purple-600">Add your first piece</Link></div>}</div><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-1"><div className="rounded-3xl border border-slate-100 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-2"><CalendarDays className="h-5 w-5 text-brand-purple-600" /><h2 className="font-black">Calendar</h2></div><div className="mt-5 grid grid-cols-7 gap-1 text-center text-xs text-slate-400">{['S','M','T','W','T','F','S'].map((day, i) => <span key={`${day}${i}`}>{day}</span>)}{Array.from({ length: 14 }, (_, i) => <span key={i} className={`grid aspect-square place-items-center rounded-lg ${i === 5 ? 'bg-brand-purple-600 font-bold text-white' : 'text-slate-600 dark:text-slate-300'}`}>{i + 1}</span>)}</div><p className="mt-4 text-xs text-slate-400">Planner coming soon</p></div><div className="rounded-3xl border border-slate-100 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-2"><WashingMachine className="h-5 w-5 text-brand-purple-600" /><h2 className="font-black">Laundry status</h2></div><div className="mt-5 flex items-center gap-5"><div className="grid h-20 w-20 place-items-center rounded-full border-[10px] border-emerald-400"><strong>{available}</strong></div><div className="space-y-2 text-sm"><p><span className="mr-2 inline-block h-2 w-2 rounded-full bg-emerald-400" />Clean <b className="ml-2">{available}</b></p><p><span className="mr-2 inline-block h-2 w-2 rounded-full bg-amber-400" />Dirty <b className="ml-2">{items.filter((item) => item.laundryStatus === 'DIRTY').length}</b></p><p className="text-xs text-slate-400">Full tracker coming soon</p></div></div></div></div></section>
  </div>;
}
