import React, { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Heart, Loader2, Sparkles, ThumbsDown, ThumbsUp, Trash2 } from 'lucide-react';
import { deleteOutfit, getSavedOutfits, rateOutfit, toggleOutfitFavorite } from '../services/api/outfits';

export default function Outfits() {
  const [favoritesOnly, setFavoritesOnly] = useState(false); const queryClient = useQueryClient();
  const { data, isLoading } = useQuery({ queryKey: ['saved-outfits', favoritesOnly], queryFn: () => getSavedOutfits({ limit: 50, ...(favoritesOnly ? { favoritesOnly: true } : {}) }) });
  const refresh = () => queryClient.invalidateQueries({ queryKey: ['saved-outfits'] });
  const favorite = useMutation({ mutationFn: ({ id, isFavorite }) => toggleOutfitFavorite(id, isFavorite), onSuccess: refresh });
  const remove = useMutation({ mutationFn: deleteOutfit, onSuccess: refresh }); const rate = useMutation({ mutationFn: ({ id, rating }) => rateOutfit(id, rating), onSuccess: refresh });
  const outfits = data?.data || [];
  return <div className="mx-auto max-w-7xl p-5 sm:p-8"><header className="flex items-end justify-between gap-4"><div><p className="text-sm font-bold text-brand-purple-600">SAVED LOOKS</p><h1 className="mt-1 text-3xl font-black">My outfits</h1><p className="mt-1 text-sm text-slate-500">Rate AI looks to give future suggestions lightweight personal context.</p></div><button onClick={() => setFavoritesOnly((value) => !value)} className="rounded-xl border px-4 py-3 text-sm font-bold"><Heart className={`mr-1 inline h-4 w-4 ${favoritesOnly ? 'fill-current text-rose-500' : ''}`} />Favorites</button></header>{isLoading ? <Loader2 className="mx-auto mt-16 h-7 w-7 animate-spin text-brand-purple-600" /> : outfits.length ? <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{outfits.map((outfit) => <article key={outfit.id} className="overflow-hidden rounded-3xl border border-slate-100 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="grid grid-cols-3 bg-slate-100">{outfit.items.slice(0, 3).map(({ clothingItem }) => <img key={clothingItem.id} src={clothingItem.imageUrl} alt={clothingItem.subcategory} className="aspect-square w-full object-cover" />)}</div><div className="p-5"><div className="flex justify-between"><div><p className="text-[10px] font-black text-brand-purple-600">{outfit.occasion}</p><h2 className="font-black">Saved outfit</h2></div><div><button onClick={() => favorite.mutate({ id: outfit.id, isFavorite: !outfit.isFavorite })} className="p-2"><Heart className={`h-5 w-5 ${outfit.isFavorite ? 'fill-current text-rose-500' : 'text-slate-400'}`} /></button><button onClick={() => remove.mutate(outfit.id)} className="p-2 text-slate-400"><Trash2 className="h-5 w-5" /></button></div></div><p className="mt-3 text-sm text-slate-500">{outfit.aiReason}</p>{outfit.aiReason && <div className="mt-4 flex items-center gap-2"><span className="mr-1 text-xs font-bold text-slate-500">Helpful?</span><button aria-label="Like suggestion" onClick={() => rate.mutate({ id: outfit.id, rating: 1 })} className={outfit.aiRating === 1 ? 'text-emerald-600' : 'text-slate-400'}><ThumbsUp className="h-5 w-5" /></button><button aria-label="Dislike suggestion" onClick={() => rate.mutate({ id: outfit.id, rating: -1 })} className={outfit.aiRating === -1 ? 'text-rose-600' : 'text-slate-400'}><ThumbsDown className="h-5 w-5" /></button></div>}<div className="mt-4 flex flex-wrap gap-2">{outfit.items.map(({ clothingItem }) => <span key={clothingItem.id} className="rounded-full bg-slate-100 px-2 py-1 text-xs">{clothingItem.subcategory}</span>)}</div></div></article>)}</div> : <div className="mt-10 rounded-3xl border border-dashed p-12 text-center"><Sparkles className="mx-auto h-8 w-8 text-brand-purple-600" /><p className="mt-3 font-bold">No saved outfits yet.</p></div>}</div>;
}
